version: "3.8"
 
services:
  postgres:
      image: postgres
      environment:
        POSTGRES_USER: movie_web_user 
        POSTGRES_DB: movie_web_backend 
        POSTGRES_PASSWORD: password 
      ports:
        - "5432:5432" 

  sudo-flix:
      build:
        context: backend/
      environment:
        MWB_POSTGRES__CONNECTION: postgresql://movie_web_user:password@postgres:5432/movie_web_backend
        MWB_CRYPTO__SESSION_SECRET: A1b2C3d4E5f6G7h8I9j0K1l2M3n4O5p6 
        MWB_META__NAME: unofficial-sudo-flix 
        MWB_POSTGRES__MIGRATE_ON_BOOT: "true"
        MIKRO_ORM_MIGRATIONS_DISABLE_FOREIGN_KEYS: "true" 
      ports:
        - "8080:8080"
      depends_on:
        - postgres

  proxy:
    build: 
      context: sudo-proxy/
    ports:
      - "3000:3000" 
  movieweb:
    build:
      context: smov/
      args:
        TMDB_READ_API_KEY: "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI5MDE0MmRjY2FkNDlhMWY4MjE4NzNmM2U5M2M2MTJhYiIsInN1YiI6IjY2Njg1ZDQ1NjQyMjlkOTQwN2MyYWNjMSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.HBSw9RVByRSKJL0GlvjC3fQwkCVMMlMIlYUwA5Fx1hY"
        CORS_PROXY_URL: "localhost:3000"
        BACKEND_URL: "localhost:8080"
    ports:
      - "80:80"
    restart: unless-stopped

